name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWM4NGIzNDUtOGIwNy00MTI0LTk5MGQtYThhNWJkOWQwNzFkIiwidGVuYW50X2lkIjoiYWM3MmU3ZDQxMDlhMjBmMDE1YWQ5N2MzOTY1MGUzN2M2NTcxOWNkMmEyNTA5N2RiYTU3MTkzNjdjYTg0NjE1NyIsImludGVybmFsX3NlY3JldCI6IjI3ODNkOWVlLTVhMGUtNDQzMi04NTM1LWYzODYxYWFhOTc1ZCJ9.q6E_Ccmx_Dp6F6_J_HOn_QYMzGW141aaZeBSRw5E4Uo"
JWT_SECRET = "typesecret"
